# Generated by Django 5.0 on 2024-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0002_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='address',
            field=models.CharField(max_length=22225, null=True),
        ),
    ]
