# Generated by Django 5.0 on 2024-09-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0004_recruiter_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=22225, null=True)),
                ('qualification', models.CharField(max_length=22225)),
                ('experience', models.CharField(max_length=22225, null=True)),
                ('hire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerapp.recruiter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
