# Generated by Django 5.0 on 2024-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
