# Generated by Django 5.0 on 2024-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0006_job_rented_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='rented_at',
            new_name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
