# Generated by Django 5.0 on 2024-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0007_rename_rented_at_job_posted_at_job_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
