# Generated by Django 5.0 on 2024-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0009_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about_job',
            field=models.CharField(max_length=22225, null=True),
        ),
    ]
