# Generated by Django 5.0 on 2024-09-05 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0010_job_about_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerapp.recruiter')),
                ('jobname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerapp.job')),
                ('seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerapp.jobseeker')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
