# Generated by Django 5.0 on 2024-09-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0011_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
