# Generated by Django 5.0 on 2024-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0012_applications_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(max_length=22225, null=True),
        ),
    ]
